version: '3.8'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: options_container
    image: options-image:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app

  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: optionsdb
      POSTGRES_USER: optionsuser
      POSTGRES_PASSWORD: optionspassword
