version: '3.8'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: options_container
    image: options-image:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app
    env_file:
      - .env
  sqlserver:
    image: mysql/mysql-server:8.0.23
    env_file:
      - .env
    ports:
      - "3306:3306"


